---
# Ansible playbook to prepare to upgrade Debian.
# This doesn't actually do the upgrade because I want to do that
# manually to manually update config files, etc.

- name: Prepare to upgrade Debian
  hosts: all
  become: true
  vars:
    old_release: bullseye
    new_release: bookworm
  tasks:
    - name: Prepare to upgrade Debian
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_release'] == old_release
      block:
        - name: Remove Puppet packages
          ansible.builtin.package:
            name:
              - puppet-agent
              - puppet-release
            state: absent

        # systemd-resolved is a separate package in bookworm and not installed
        # when upgrading.
        # https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html#systemd-resolved
        - name: Install systemd-resolved from bullseye-backports
          ansible.builtin.apt:
            name: systemd-resolved
            default_release: bullseye-backports

        - name: Find sources files
          ansible.builtin.find:
            paths: /etc/apt
            recurse: true
            patterns: "*.list"
          register: sources

        - name: Replace release codename in sources files
          ansible.builtin.replace:
            regexp: "{{ old_release }}"
            replace: "{{ new_release }}"
            path: "{{ item.path }}"
          loop: "{{ sources.files }}"

        - name: Update package cache
          ansible.builtin.apt:
            update_cache: true
            autoclean: true

        - name: Done
          ansible.builtin.debug:
            msg:
              - "Now, the manual upgrade process: sudo apt upgrade --without-new-pkgs && sudo apt full-upgrade"
              - "Reference: https://www.debian.org/releases/{{ new_release }}/amd64/release-notes/ch-upgrading.en.html"
              - "Reinstall Puppet with wget https://apt.puppet.com/puppet8-release-bookworm.deb && sudo apt install ./puppet8-release-bookworm.deb"
