---
# Ansible playbook to prepare to upgrade Debian.
# This doesn't actually do the upgrade because I want to do that
# manually to manually update config files, etc.

- name: Prepare to upgrade Debian
  hosts: all
  become: true
  vars:
    old:
      codename: bookworm
      version: 12
    new:
      codename: trixie
      version: 13
  tasks:
    - name: Prepare to upgrade Debian
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_release'] == old['codename']
      block:
        - name: Stop OpenVox
          ansible.builtin.service:
            name: puppet
            state: stopped

        - name: Find sources files
          ansible.builtin.find:
            paths: /etc/apt
            recurse: true
            patterns: "*.list"
          register: sources

        - name: Replace release codename in sources files
          ansible.builtin.replace:
            regexp: "{{ old['codename'] }}"
            replace: "{{ new['codename'] }}"
            path: "{{ item.path }}"
          loop: "{{ sources.files }}"

        - name: Replace version number in OpenVox source file
          ansible.builtin.replace:
            regexp: "debian{{ old['version'] }}"
            replace: "debian{{ new['version'] }}"
            path: /etc/apt/sources.list.d/openvox.list

        - name: Update package cache
          ansible.builtin.apt:
            update_cache: true
            autoclean: true

        - name: Done
          ansible.builtin.debug:
            msg:
              - "Now, the manual upgrade process: sudo apt upgrade --without-new-pkgs && sudo apt full-upgrade"
              - "Reference: https://www.debian.org/releases/{{ new['codename'] }}/release-notes/upgrading.html"
